# List of phrases to remove
phrases_to_remove = [
    "thanks for watching",
    "thank you",
    "we look forward to having you guys next",
    "he's so good for you",
    "good to see you",
    "good night",
    "coming up with his latest",
    "We're having a good time",
    "I even just want to make sure that this gives you welcome to the next episode",
    "as it is brought to the",
    "want to find out the",
    "We've got a lot of work to do",
    "help us out and we will have a",
    "this video, be sure to give it a like and subscribe!",
    "be sure to give it a like and subscribe!",
    "like and subscribe!",
    "don't forget to subscribe",
    "hit the like button",
    "make sure to comment below",
    "stay tuned for more",
    "let's dive into it",
    "that wraps it up",
    "we'll see you in the next one",
    "hope you enjoyed this video",
    "welcome back to our channel",
    "thanks for tuning in",
    "follow us on social media",
    "let's get started",
    "without further ado",
    "if you're new here",
    "turn on notifications",
    "as always, thanks for watching",
    "be sure to stick around",
    "we hope you find this helpful",
    "I hope that makes sense",
    "drop a comment if you have questions",
    "let me know your thoughts",
    "if you like this content",
    "until next time",
    "that's all for now",
    "as we wrap up",
    "thanks for being here",
    "catch you in the next video",
    "be sure to follow for more updates",
    "we’ll be back soon",
    "this is just the beginning",
    "if you're enjoying this",
    "if you found this useful",
    "make sure to hit the bell icon",
    "subscribe for more content",
    "we really appreciate your support",
    "let us know what you think",
    "see you in the next episode",
    "leave a like if you enjoyed",
    "don’t miss out on our next video",
    "this is just a quick reminder",
    "we’ll catch you next time",
    "and with that, we’ll wrap it up",
    "that’s it for today",
    "thanks for spending your time with us",
    "join us next time",
    "hope to see you soon",
    "be sure to share this video",
    "let us know in the comments",
    "if you learned something new",
    "don’t forget to share",
    "we'll be back with more",
    "keep watching for more tips",
    "we hope you got value from this",
    "make sure to stay connected",
    "more content coming your way",
    "stay updated with our channel",
    "and that’s all from us today",
    "thank you for being part of this journey",
    "if you enjoyed this episode",
    "we're just getting started",
    "feel free to subscribe",
    "and that's a wrap",
    "stay tuned for upcoming episodes",
    "check out our other videos",
    "thanks for joining us",
    "don’t forget to check out",
    "appreciate your time",
    "please consider subscribing",
    "like, share, and comment below",
    "make sure to check back",
    "we'll see you again soon",
    "hope you liked what you saw",
    "your support means a lot",
    "we appreciate you tuning in",
    "keep following for more updates",
    "and that concludes today’s video",
    "thank you so much for your support",
    "more exciting content ahead",
    "if you haven’t subscribed yet",
    "it really helps the channel",
    "don't miss our next video",
    "as always, stay awesome",
    "we’ll see you next time",
    "let’s keep the conversation going",
    "join the community",
    "appreciate your feedback",
    "stick around for more",
    "make sure you’re subscribed",
    "until the next video",
    "Stay tuned for more news or ",
    "Stay tuned ",
    "hit the subscribe button",
    "click the notification bell",
    "let's jump right into it",
    "leave your thoughts below",
    "if this was helpful",
    "don’t forget to give us a thumbs up",
    "let us know in the comments below",
    "keep an eye out for",
    "we’ll be back with another video",
    "hope you enjoyed watching",
    "follow for more updates",
    "share this with your friends",
    "we’re here to help",
    "thanks for all your support",
    "let’s move forward",
    "tell us what you think",
    "it means a lot to us",
    "we appreciate every like",
    "don’t forget to engage",
    "thanks for being part of the community",
    "we value your opinion",
    "your feedback helps us grow",
    "support us by subscribing",
    "we’ll see you around",
    "let us know if this helped",
    "don’t go anywhere just yet",
    "be sure to check this out",
    "we’re just getting started here",
    "make sure you don’t miss out",
    "stick with us for more",
    "we hope this video was insightful",
    "remember to subscribe",
    "your likes help the algorithm",
    "stay in touch",
    "share your thoughts below",
    "we’ll catch up next time",
    "if this resonated with you",
    "we’ve got more in store",
    "stay subscribed",
    "we hope to see you again",
    "keep the support coming",
    "keep following us",
    "check back for updates",
    "let’s keep pushing forward",
    "thanks for being part of our journey",
    "don’t miss upcoming videos",
    "help us spread the word",
    "be part of the journey",
    "let us know if you liked this",
    "keep up with our content",
    "subscribe to stay updated",
    "share this if you found it useful",
    "Stay tuned for more videos on how to add your own videos",
]
